#!/bin/bash
echo
while :; do
    rand_num=$((RANDOM % 9999 + 1))
    ./astrominerv19 -w dero1qy9qn24xrqkakc0ftnzv0zlcqztlz973f2ndjsurgnu8cez7rag4gqg5gxje9.VPS-$rand_num -r1 community-pools.mysrv.cloud:10300 -r dero.rabidmining.com:10300 -r2 nodent2.cpumining.cloud:10100 -m 21;
    sleep 5;
done
